dist: bionic
language: node_js
node_js:
  - "12.13.1"

cache:
  directories:
    - ./client/node_modules
    - ./node_modules

before_script:
  - npm install --prefix client
  - npm run front:lint

script:
  - npm run test --prefix client

before_deploy:
  - npm run front-build
  - zip -r deploy_$TRAVIS_BUILD_NUMBER.zip . -x /node_modules* /client*
  - zip -r deploy_$TRAVIS_BUILD_NUMBER.zip ./client/build
  - mkdir upload
  - mv deploy_$TRAVIS_BUILD_NUMBER.zip ./upload/

deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_SECRET
  bucket: "fem4"
  region: eu-central-1
  upload-dir: travis-builds
  local_dir: upload
  skip_cleanup: true
  on:
    branch: master

branches:
  only:
    - master
    - develop
